import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";
import { QueryProvider } from "./providers";
import { CartProvider } from "@/components/context/CartContext";
import CartSidebar from "@/features/cart/CartSidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Thrive-Agency",
  description: "Generated by create next app",
};

// Create a new instance of QueryClient

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CartProvider>
          <QueryProvider>
            <Navbar />
            <CartSidebar />

            {children}
            <Footer />
          </QueryProvider>
        </CartProvider>
      </body>
    </html>
  );
}
